name: CI
 
on:
  #Theoretically this should run on feature branch only.
  # push:
  #   branches-ignore:
  #     - main
  # pull_request:
  #   branches-ignore:
  #     - main
  push:
    branches:
      - main
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        -env:
          JWT_SECRET: 'no_time_should_be_added_to_do_secret'
        run: |
          pytest -q
